kind: ConfigMap
apiVersion: v1
metadata:
  name: quay-config-template
  namespace: quay
data:
  config.yaml: |
    FEATURE_USER_INITIALIZE: true
    BROWSER_API_CALLS_XHR_ONLY: false
    SUPER_USERS:
      - quayadmin
    FEATURE_USER_CREATION: false
    DISTRIBUTED_STORAGE_CONFIG:
      S3Storage:
        - S3Storage
        - host: "{{ .host }}"
          s3_access_key: "{{ .accessKey }}"
          s3_bucket: "{{ .bucket }}"
          s3_secret_key: "{{ .secretKey }}"
          s3_region: "{{ .region }}"
          storage_path: /datastorage/registry
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    DISTRIBUTED_STORAGE_PREFERENCE:
        - S3Storage

